[gspread]
type = "service_account"
project_id = "analytics-project-survey-forms"
private_key_id = "adc282304408c44b5fd028e9fd6e47a74881b8ea"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkq...<your key continued with \\n for line breaks>...\\n-----END PRIVATE KEY-----\\n"
client_email = "google-sheet-python-access@analytics-project-survey-forms.iam.gserviceaccount.com"
client_id = "113768895930459522640"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/google-sheet-python-access%40analytics-project-survey-forms.iam.gserviceaccount.com"
gsheet_key = "120CdAS6mUd8BMex1ftYZ6pRLsucxFiLlgCQp8PYVRG4"
